const products = [
  {
    id: 'weight-loss-bundle',
    name: '30-DAY RESET BUNDLE',
    description: 'Jumpstart your wellness journey with the 30-Day Reset Bundle — our bestselling Daily N’Oats flavors in a convenient 30-pack bundle.',
    category: 'breakfast',
    price: 138.0,
    netCarbs: 2,
    protein: 20,
    fiber: 4,
    allergens: ["nuts"],
    dietary: ["high-protein", "keto", "dairy-free", "sugar-free", "vegan", "no-preservatives", "soy-free"]
  },
  {
    id: 'apple-cinnamon',
    name: 'Apple + Cinnamon',
    description: 'Taste the sweet and familiar flavor of grandma\'s apple pie, minus the carbs! Our Apple + Cinnamon flavor is the perfect balance of tart apple and cinnamon spice.',
    category: 'breakfast',
    price: 72.5,
    netCarbs: 2,
    protein: 20,
    fiber: 4,
    flavor: 'apple; cinnamon'
  },
  {
    id: 'apple-cinnamon-noats',
    name: "Apple + Cinnamon N'Oats",
    description: 'Taste the sweet and familiar flavor of grandma\'s apple pie, minus the carbs! Our Apple + Cinnamon flavor is the perfect balance of tart apple and cinnamon spice.',
    category: 'breakfast',
    price: 7.0,
    netCarbs: 2,
    protein: 20,
    fiber: 4
  },
  {
    id: 'banana-macadamia',
    name: 'Banana + Macadamia',
    description: 'Experience the delightful duo of bananas and macadamias - without the guilt! Enjoy all the classically sweet and nutty flavors without the added sugar.',
    category: 'breakfast',
    price: 72.5,
    netCarbs: 2,
    protein: 20,
    fiber: 4,
    flavor: 'banana',
    allergens: ["nuts"],
    dietary: ["soy-free", "no-preservatives", "dairy-free", "sugar-free", "keto", "gluten-free", "vegan", "high-protein"]
  },
  {
    id: 'banana-macadamia-noats',
    name: "Banana + Macadamia N'Oats",
    description: 'Experience the delightful duo of bananas and macadamias - without the guilt! Enjoy all the classically sweet and nutty flavors without the added sugar.',
    category: 'breakfast',
    price: 7.0,
    netCarbs: 2,
    protein: 20,
    fiber: 4
  },
  {
    id: 'blueberry-spice',
    name: 'Blueberry + Spice',
    description: 'Blueberry + Spice, the sweet-spicy breakfast that packs a flavor punch without the carbs.  Supercharge your taste buds with the perfect union of real blueberries and cinnamon, for a delightful treat t',
    category: 'breakfast',
    price: 72.5,
    netCarbs: 2,
    protein: 20,
    fiber: 4,
    flavor: 'blueberry; cinnamon',
    dietary: ["gluten-free", "non-gmo", "sugar-free", "vegan", "high-protein", "keto", "dairy-free"]
  },
  {
    id: 'blueberry-spice-noats',
    name: "Blueberry + Spice N'Oats",
    description: 'Blueberry + Spice, the sweet-spicy breakfast that packs a flavor punch without the carbs.  Supercharge your taste buds with the perfect union of real blueberries and cinnamon, for a delightful treat t',
    category: 'breakfast',
    price: 7.0,
    netCarbs: 2,
    protein: 20,
    fiber: 4
  },
  {
    id: 'brown-sugar-cinnamon',
    name: 'Brown Sugar + Cinnamon',
    description: 'Transport yourself to a cozy bakery with Brown Sugar + Cinnamon Daily N\'Oats - the perfect blend of warm & sweet, with a hint of spice reminiscent of your favorite cinnamon roll! Enjoy the flavors of',
    category: 'breakfast',
    price: 72.5,
    netCarbs: 2,
    protein: 20,
    fiber: 4,
    flavor: 'cinnamon',
    dietary: ["sugar-free", "high-protein"]
  },
  {
    id: 'brown-sugar-cinnamon-noats',
    name: "Brown Sugar + Cinnamon N'Oats",
    description: 'Transport yourself to a cozy bakery with Brown Sugar + Cinnamon Daily N\'Oats - the perfect blend of warm & sweet, with a hint of spice reminiscent of your favorite cinnamon roll! Enjoy the flavors of',
    category: 'breakfast',
    price: 7.0,
    netCarbs: 2,
    protein: 20,
    fiber: 4
  },
  {
    id: 'cacao-peanut-butter',
    name: 'Cacao + Peanut Butter',
    description: 'Satisfy your cravings without the carbs! Our Cacao + Peanut Butter blend brings you the classic combo of childhood memories in an updated form! Enjoy the luxurious taste of chocolatey cacao and the nu',
    category: 'breakfast',
    price: 72.5,
    netCarbs: 2,
    protein: 20,
    fiber: 4,
    flavor: 'chocolate'
  },
  {
    id: 'cacao-peanut-butter-noats',
    name: "Cacao + Peanut Butter N'Oats",
    description: 'Satisfy your cravings without the carbs! Our Cacao + Peanut Butter blend brings you the classic combo of childhood memories in an updated form! Enjoy the luxurious taste of chocolatey cacao and the nu',
    category: 'breakfast',
    price: 7.0,
    netCarbs: 2,
    protein: 20,
    fiber: 4
  },
  {
    id: 'daily-noats',
    name: "DAILY N'OATS",
    description: 'Start your day with DAILY N\'OATS! This low-carb, oatmeal alternative is packed with 20g of protein and heart-healthy fats from real coconuts , but with only 2g of net carbs and zero added sugar —makin',
    category: 'breakfast',
    price: 72.5,
    netCarbs: 2,
    protein: 20,
    fiber: 4,
    dietary: ["dairy-free", "keto", "gluten-free", "vegan", "no-preservatives", "soy-free", "high-protein"]
  },
  {
    id: 'daily-noats-gift-card',
    name: "DAILY N'OATS GIFT CARD",
    description: 'Treat someone (or yourself!) to a nutritious start with a Daily N\'Oats Gift Card - perfect for any taste bud!',
    category: 'breakfast',
    price: 10.0,
    netCarbs: 2,
    protein: 20,
    fiber: 4
  },
  {
    id: 'daily-noats-singles',
    name: "DAILY N'OATS SINGLES",
    description: 'Are you curious about Daily N\'Oats, but hesitant to commit to a bundle? Why not give a Daily N\'Oats Single a try? Note: Coupon or Promo codes do not apply to singles.',
    category: 'breakfast',
    price: 7.0,
    netCarbs: 2,
    protein: 20,
    fiber: 4
  },
  {
    id: 'daily-noats-6-pack',
    name: "Daily N'Oats 6-Pack",
    description: 'Low-carb, high-protein breakfast alternative with real superfood ingredients',
    category: 'breakfast',
    price: 30.0,
    netCarbs: 2,
    protein: 20,
    fiber: 4,
    flavor: 'apple-cinnamon; blueberry-spice; cacao-peanut-butter; banana-macadamia; naked-n-oats; wild-strawberry; brown-sugar-cinnamon; maple-pecan; vanilla-almond'
  },
  {
    id: 'fab-four-bundle',
    name: 'FAB FOUR BUNDLE',
    description: 'Our FAB FOUR BUNDLE features the all-time top four flavors melded into one delicious package: Brown Sugar + Cinnamon , Vanilla + Almond , Maple + Pecan , and Naked N\'Oats .',
    category: 'breakfast',
    price: 72.5,
    netCarbs: 2,
    protein: 20,
    fiber: 4
  },
  {
    id: 'fall-bundle',
    name: 'FALL BUNDLE',
    description: 'It\'s Fall, Y\'all! Bring the flavors of the season into your home with this FALL BUNDLE that includes three delicious varieties: Pumpkin + Spice, Apple + Cinnamon, and Maple + Pecan.',
    category: 'breakfast',
    price: 72.5,
    netCarbs: 2,
    protein: 20,
    fiber: 4
  },
  {
    id: 'gingerbread',
    name: 'Gingerbread',
    description: 'Bring winter cheer to your home with our delicious Gingerbread N\'Oats .  Enjoy the creamy, cozy flavor of warm spices like ginger, cinnamon, cloves and allspice! Spice up the season with our sweet tre',
    category: 'breakfast',
    price: 72.5,
    netCarbs: 2,
    protein: 20,
    fiber: 4,
    flavor: 'ginger',
    dietary: ["soy-free", "no-preservatives", "dairy-free", "sugar-free", "keto", "gluten-free", "vegan", "high-protein"]
  },
  {
    id: 'gingerbread-noats',
    name: "Gingerbread N'Oats",
    description: 'Bring winter cheer to your home with our delicious Gingerbread .  Enjoy the creamy, cozy flavor of warm spices like ginger, cinnamon, cloves and allspice! Spice up the season with our sweet treat that',
    category: 'breakfast',
    price: 7.0,
    netCarbs: 2,
    protein: 20,
    fiber: 4
  },
  {
    id: 'mixed-bundle',
    name: 'MIXED BUNDLE',
    description: 'Take a gamble on this game changing bundle of delights! Our Mixed Bundle includes a variety pack of flavors, so you can mix it up and enjoy something different every day. It\'s sure to be a wild ride!',
    category: 'breakfast',
    price: 72.5,
    netCarbs: 2,
    protein: 20,
    fiber: 4
  },
  {
    id: 'maple-pecan',
    name: 'Maple + Pecan',
    description: 'Eat your heart out with a combination of creamy maple and crunchy pecans in our Maple + Pecan Overnight N\'Oats Shake.',
    category: 'breakfast',
    price: 72.5,
    netCarbs: 2,
    protein: 20,
    fiber: 4,
    flavor: 'cinnamon'
  },
  {
    id: 'maple-pecan-noats',
    name: "Maple + Pecan N'Oats",
    description: 'Eat your heart out with a combination of creamy maple and crunchy pecans in our Maple + Pecan Overnight N\'Oats Shake.',
    category: 'breakfast',
    price: 7.0,
    netCarbs: 2,
    protein: 20,
    fiber: 4
  },
  {
    id: 'mix-and-match-bundle',
    name: 'Mix and Match Bundle',
    description: 'Mix.  Match.',
    category: 'breakfast',
    price: 72.5,
    netCarbs: 2,
    protein: 20,
    fiber: 4,
    flavor: 'brown-sugar-cinnamon; pineapple-coconut',
    allergens: ["nuts"],
    dietary: ["keto", "gluten-free"]
  },
  {
    id: 'naked-noats-1',
    name: "Naked N'Oats",
    description: 'Naked N\'Oats, a blank canvas for whatever culinary vision you have! These unsweetened n\'oats are perfect for savory creations, baking, or even a healthy snack - with 20g of protein, 3g of net carbs an',
    category: 'breakfast',
    price: 7.0,
    netCarbs: 2,
    protein: 20,
    fiber: 4
  },
  {
    id: 'naked-noats',
    name: "Naked N'Oats",
    description: 'Naked N\'Oats, a blank canvas for whatever culinary vision you have! These unsweetened n\'oats are perfect for savory creations, baking, or even a healthy snack - with 20g of protein, 3g of net carbs an',
    category: 'breakfast',
    price: 72.5,
    netCarbs: 2,
    protein: 20,
    fiber: 4
  },
  {
    id: 'overnight-jar',
    name: "Overnight N'Oats Jar",
    description: 'Elevate your breakfast routine with the Violet Miron glass DAILY N\'OATS Overnight Jar, and embark on a journey to breakfast excellence.',
    category: 'breakfast',
    price: 25.0,
    netCarbs: 2,
    protein: 20,
    fiber: 4
  },
  {
    id: 'peaches-cream',
    name: 'Peaches + Cream',
    description: 'Our Peaches + Cream flavor captures the taste of sun-ripened peaches and velvety cream in every bite.',
    category: 'breakfast',
    price: 72.5,
    netCarbs: 2,
    protein: 20,
    fiber: 4,
    dietary: ["keto", "high-protein", "sugar-free"]
  },
  {
    id: 'peaches-cream-noats',
    name: "Peaches + Cream N'Oats",
    description: 'Beat the heat with our Peaches + Cream Overnight N\'Oats Shake: it\'s breakfast on the go for when you don\'t want to hang around the stove! An irresistibly creamy blend of peaches and overnight N\'Oats,',
    category: 'breakfast',
    price: 7.0,
    netCarbs: 2,
    protein: 20,
    fiber: 4
  },
  {
    id: 'pumpkin-spice',
    name: 'Pumpkin + Spice',
    description: 'Pumpkin + Spice N\'Oats -- it\'s like having a slice of pumpkin pie in a bowl! Our deliciously cozy fall favorite is made with warm spices and crunchy pecans -- it\'s fall breakfast heaven! Who needs gra',
    category: 'breakfast',
    price: 72.5,
    netCarbs: 2,
    protein: 20,
    fiber: 4,
    flavor: 'cinnamon',
    dietary: ["soy-free", "no-preservatives", "dairy-free", "sugar-free", "keto", "gluten-free", "vegan", "high-protein"]
  },
  {
    id: 'pumpkin-spice-noats',
    name: "Pumpkin + Spice N'Oats",
    description: 'Pumpkin + Spice N\'Oats -- it\'s like having a slice of pumpkin pie in a bowl! Our deliciously cozy fall favorite is made with warm spices and crunchy pecans -- it\'s fall breakfast heaven! Who needs gra',
    category: 'breakfast',
    price: 7.0,
    netCarbs: 2,
    protein: 20,
    fiber: 4
  },
  {
    id: '30-day-glp-bundle',
    name: "THE DAILY N'OATS GLP-1 BUNDLE",
    description: 'Jumpstart your wellness journey with the 30-Day Reset Bundle — our bestselling Daily N’Oats flavors in a convenient 30-pack bundle.',
    category: 'breakfast',
    price: 138.0,
    netCarbs: 2,
    protein: 20,
    fiber: 4,
    allergens: ["nuts"],
    dietary: ["high-protein", "keto", "dairy-free", "sugar-free", "vegan", "no-preservatives", "soy-free", "vegetarian"]
  },
  {
    id: 'the-fab-four-bundle',
    name: 'THE FAB FOUR BUNDLE',
    description: 'Daily N\'Oats offers all of the benefits of oatmeal, a quick, easy and low-calorie breakfast — but with more nutritious ingredients that\'s low carb.',
    category: 'breakfast',
    price: 72.5,
    netCarbs: 2,
    protein: 20,
    fiber: 4,
    flavor: 'cinnamon; vanilla; almond'
  },
  {
    id: 'the-mixed-bundle',
    name: 'THE MIXED BUNDLE',
    description: 'Daily N\'Oats offers all of the benefits of oatmeal, a quick, easy and low-calorie breakfast — but with more nutritious ingredients that\'s low carb.',
    category: 'breakfast',
    price: 72.5,
    netCarbs: 2,
    protein: 20,
    fiber: 4,
    allergens: ["nuts"],
    dietary: ["high-protein", "keto", "dairy-free", "sugar-free", "vegan", "no-preservatives", "soy-free"]
  },
  {
    id: 'vanilla-almond',
    name: 'Vanilla + Almond',
    description: 'Indulge guilt-free with Vanilla + Almond N\'Oats! This flavor combo offers the smooth satisfaction of creamy vanilla coupled with the delightful crunch of roasted almonds.',
    category: 'breakfast',
    price: 72.5,
    netCarbs: 2,
    protein: 20,
    fiber: 4,
    flavor: 'vanilla; almond',
    allergens: ["nuts"],
    dietary: ["dairy-free", "sugar-free", "keto", "gluten-free", "vegan", "no-preservatives", "soy-free", "high-protein"]
  },
  {
    id: 'vanilla-almond-noats',
    name: "Vanilla + Almond N'Oats",
    description: 'Indulge guilt-free with Vanilla + Almond N\'Oats! This flavor combo offers the smooth satisfaction of creamy vanilla coupled with the delightful crunch of roasted almonds.',
    category: 'breakfast',
    price: 7.0,
    netCarbs: 2,
    protein: 20,
    fiber: 4
  },
  {
    id: 'winter-bundle',
    name: 'WINTER BUNDLE',
    description: 'Winter just got a whole lot cooler with this WINTER BUNDLE! This festive package comes with just enough Gingerbread , scrumptious Cacao + Peanut Butter , and sweet Banana + Macadamia to satisfy all yo',
    category: 'breakfast',
    price: 72.5,
    netCarbs: 2,
    protein: 20,
    fiber: 4
  },
  {
    id: 'wild-strawberry',
    name: 'Wild Strawberry',
    description: 'Tantalize your taste buds with Wild Strawberry Overnight N\'Oats Shake! Enjoy the comforting taste of wild strawberries with none of the carbs.',
    category: 'breakfast',
    price: 72.5,
    netCarbs: 2,
    protein: 20,
    fiber: 4,
    flavor: 'strawberry',
    dietary: ["dairy-free", "soy-free", "no-preservatives", "sugar-free", "keto", "gluten-free", "vegan", "high-protein"]
  },
  {
    id: 'wild-strawberry-noats',
    name: "Wild Strawberry N'Oats",
    description: 'Tantalize your taste buds with Wild Strawberry Overnight N\'Oats Shake! Enjoy the comforting taste of wild strawberries with none of the carbs.',
    category: 'breakfast',
    price: 7.0,
    netCarbs: 2,
    protein: 20,
    fiber: 4
  }
];

export default products;